### ISSUE TITLE
php70 Atualização chave pub

### ISSUE THREAD

**Issue by adhenawer** [1giba/miniphp#1]
@1giba atualizaram no repo do ambientum o local da chave do php-alpine, tem que atualizar o dockerfile do php70 -> `wget -O /etc/apk/keys/php-alpine.rsa.pub \` https://github.com/codecasts/ambientum/blob/master/php/7.0/Dockerfile#L30

![screen shot 2017-05-29 at 20 52 30](https://cloud.githubusercontent.com/assets/708516/26563944/e68f7482-44b0-11e7-9745-dbc91cf8f7f8.png)

**Comment by 1giba** [comment]
b802368 

Valeu!
